# Implement Firewall Rules Using iptables (Simulation & Verification)

print("==================================================")
print("        iptables Firewall Configuration")
print("==================================================")
print("Commands Executed:")
print("1. sudo apt update && sudo apt install iptables -y")
print("2. sudo iptables -F && sudo iptables -X")
print("3. sudo iptables -A INPUT -i lo -j ACCEPT")
print("4. sudo iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT")
print("5. sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT")
print("6. sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT")
print("7. sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT")
print("8. sudo iptables -A INPUT -p tcp --dport 9090 -j DROP")
print("9. sudo iptables -P INPUT DROP")
print("10. sudo iptables -P FORWARD DROP")
print("11. sudo iptables -P OUTPUT ACCEPT")
print()
print("Firewall Verification Table:")
print("Chain INPUT (policy DROP 0 packets, 0 bytes)")
print(" pkts bytes target prot opt in  out source    destination")
print("    5   300 ACCEPT tcp  --  *   *   0.0.0.0/0 0.0.0.0/0   tcp dpt:8080")
print("    3   180 DROP   tcp  --  *   *   0.0.0.0/0 0.0.0.0/0   tcp dpt:9090")
print("--------------------------------------------------")
print("Port 8080 Test (Allowed):  HTTP/1.0 200 OK")
print("Port 9090 Test (Blocked):  Connection timed out (DROP)")
print("==================================================")
