# Study of Metasploit Framework and Windows Exploit Modules

print("==================================================")
print("      Metasploit Framework Exploration Study")
print("==================================================")
print("msfconsole started.")
print()
print("Search Command:")
print("  search type:exploit platform:windows")
print()
print("Exploit Modules Identified:")
print("  1. exploit/windows/smb/ms17_010_eternalblue - MS17-010 EternalBlue")
print("  2. exploit/windows/smb/ms08_067_netapi     - MS08-067 Server Service")
print("  3. exploit/windows/http/rejetto_hfs_exec   - Rejetto HFS Exec")
print()
print("Module Details (info exploit/windows/smb/ms17_010_eternalblue):")
print("  Name:     MS17-010 EternalBlue SMB Remote Windows Code Execution")
print("  Platform: Windows")
print("  Arch:     x86, x64")
print("  Options:  RHOSTS (Target host IP), RPORT (Port 445)")
print("==================================================")
